created TimerStyled & added css needed
isdi-coders-202207-bcn-coding-adventure/alex-caldas-front pull request #3
Opened 2022-08-22 13:28 UTC by areketsuku

2022-08-22 13:29 UTC, areketsuku commented
@mariogl  su css, señor
![purepng](https://user-images.githubusercontent.com/56109223/185932800-aa649ffd-4275-4168-8fab-f2af0bdd9f17.png)

2022-08-22 13:50 UTC, areketsuku commented
![preview-229570858](https://user-images.githubusercontent.com/56109223/185937230-27ad7a08-42c6-4ef4-b18d-6a74fff6afb7.jpg)

2022-08-22 13:57 UTC, areketsuku commented
![4f2255198052620c276ac9b3ef25a313-3334296708](https://user-images.githubusercontent.com/56109223/185938916-536928a7-3aa5-4df1-82e2-fb926eb61147.gif)

2022-08-22 13:59 UTC, luisdudamel requested changes

2022-08-22 13:59 UTC, luisdudamel commented on src/components/Timer/TimerStyled.css
> +  font-family: "Rajdhani", sans-serif;
Hola, Alex.
Ya hemos establecido la fuente a utilizar.

2022-08-22 13:59 UTC, luisdudamel commented on src/components/Timer/TimerStyled.css
> +  gap: 15px;
Podemos sacarle el estilo a las listas.

2022-08-22 14:00 UTC, mariogl requested changes

2022-08-22 14:00 UTC, mariogl commented on public/index.html
> +    <link
¿Qué hace esto aquí?

2022-08-22 14:00 UTC, mariogl commented on src/components/Timer/TimerStyled.css
> +ul {
El enunciado pide hacerlo con styled-components.

2022-08-22 14:00 UTC, mariogl commented on src/index.css
> +html {
Ésta no es la tipografía de la web.

2022-08-22 14:19 UTC, areketsuku commented
![my-work-here-2n7awy-3590560876](https://user-images.githubusercontent.com/56109223/185943974-9e9a64fd-a419-48d0-857f-1410d833ed37.jpg)

2022-08-22 14:27 UTC, areketsuku commented
ta bien?
![giphy](https://user-images.githubusercontent.com/56109223/185945795-426e91f0-d198-4671-b341-866fb2db1513.gif)

2022-08-22 14:41 UTC, luisdudamel requested changes

2022-08-22 14:41 UTC, luisdudamel commented on src/components/Timer/TimerStyled.css
>    width: fit-content;
Hola Alex.
El enunciado pide hacerlo con styled components.

2022-08-22 14:48 UTC, areketsuku commented
@luisdudamel hecho!
![giphy](https://user-images.githubusercontent.com/56109223/185950739-880314c8-94dc-4345-a41c-26ff6bd82efa.gif)

2022-08-22 14:51 UTC, luisdudamel requested changes

2022-08-22 14:51 UTC, luisdudamel commented on src/components/Timer/TimerStyled.js
> +  .timer__data {
Hola Alex.
Si vamos a repetir el mismo nombre de selector, utilizamos nesting de selectores.
No repetimos todas las veces el mismo selector.

2022-08-22 14:56 UTC, areketsuku commented on src/components/Timer/TimerStyled.js
> +  .timer__data {
Hola Luis.
Gracias, lo he revisado. He pusheado el commit, por lo que el pull request esta preparado.
Revisalo cuando puedas, porfavor.

Gracias.

2022-08-22 14:57 UTC, luisdudamel approved these changes
4. Dale la funcionalidad. Guarda la fecha clave en una constante que puedas usar en cualquier componente.

2022-08-22 14:59 UTC, areketsuku commented
Hola Luis,

no me sera possible mergear la pull request por que falta el aproval del change request que puso @mariogl . Como lo gestiono? Mergeo en local y sigo trabajando?

Gracias.

2022-08-22 15:00 UTC, merged

2022-08-24 17:59 UTC, mariogl commented
@areketsuku dijimos que se tenía que ver todo el viewport con el color de fondo y el contador en el centro, con el h1 en blanco.

2022-08-25 10:28 UTC, mariogl commented
> su css

@areketsuku

2022-08-25 11:52 UTC, areketsuku commented
> @areketsuku dijimos que se tenía que ver todo el viewport con el color de fondo y el contador en el centro, con el h1 en blanco.

voy!