adde funcitonality to Timer
isdi-coders-202207-bcn-coding-adventure/alex-caldas-front pull request #4
Opened 2022-08-23 11:42 UTC by areketsuku

2022-08-23 13:49 UTC, areketsuku commented
@mariogl @luisdudamel ,

Buenas tardes,
Aquí tenéis la pull request. Echadle un ojo cuando podáis, por favor.
Gracias

2022-08-23 14:03 UTC, NachoLosada requested changes
@areketsuku Revisa bien que estés operando con fechas en todo momento. Échale un ojo también que tus minutos/segundos empiezan a contar desde 60 y se van a dar situaciones esperpénticas como que faltan 3 horas, 60 minutos y 60 segundos

2022-08-23 15:00 UTC, areketsuku commented
> @areketsuku Revisa bien que estés operando con fechas en todo momento. Échale un ojo también que tus minutos/segundos empiezan a contar desde 60 y se van a dar situaciones esperpénticas como que faltan 3 horas, 60 minutos y 60 segundos

disculpa, olvide responder. Lo estoy mirando. Gracias!

2022-08-24 14:21 UTC, mariogl approved these changes

2022-08-24 14:22 UTC, mariogl commented
Fase 5. Testea el componente contador.

2022-08-24 14:22 UTC, merged